### ISSUE TITLE
App subscribes me to same trip multiple times

### ISSUE THREAD

**Issue by haydenwoodhead** [autlamps/delay-mobile-android#13]
After clicking subscribe on a trip once it appears I am resubscribed to it every time I click on the subscriptions button. Hence my number of subscriptions listed increases every time.

**Comment by haydenwoodhead** [comment]
It appears as though this may just be client side and something to do with your recylcer view.

**Comment by EVOEGO** [comment]
Fixed issue, just needed to alter PostSubscriptions Method
